blueprint:
  name: TTS ToDo-Liste
  description: Liest die Todo-Liste vor und markiert alle Einträge als erledigt
  domain: automation
  input:
    todo_entity:
      name: Todo-Liste
      description: Die Todo-Listen Entität
      selector:
        entity:
          domain: todo
    occupancy_sensor:
      name: Anwesenheitssensor
      description: Sensor der Anwesenheit erkennt
      selector:
        entity:
          domain: binary_sensor
    person_entity:
      name: Person
      description: Person die zu Hause sein muss
      selector:
        entity:
          domain: person
    media_player:
      name: Mediaplayer
      description: Mediaplayer auf dem vorgelesen wird
      selector:
        entity:
          domain: media_player
    tts_engine:
      name: TTS Engine
      selector:
        entity:
          domain: tts
    conversation_agent:
      name: Konversations-Agent
      selector:
        entity:
          domain: conversation

alias: TTS ToDo-Liste
description: ""
variables:
  todo_entity: !input todo_entity
triggers:
  - trigger: state
    entity_id: !input occupancy_sensor
    to: "on"
conditions:
  - condition: state
    entity_id: !input person_entity
    state: "home"
  - condition: template
    value_template: "{{ states(todo_entity) | int(0) > 0 }}"
actions:
  - action: todo.get_items
    data:
      status: needs_action
    target:
      entity_id: !input todo_entity
    response_variable: todo_items
  - data:
      language: de
      text: "{{ todo_items }}"
      agent_id: !input conversation_agent
    response_variable: message
    action: conversation.process
  - action: tts.speak
    metadata: {}
    data:
      cache: false
      message: "{{ message.response.speech.plain.speech }}"
      media_player_entity_id: !input media_player
    target:
      entity_id: !input tts_engine
    enabled: true
  - repeat:
      for_each: "{{ todo_items[todo_entity]['items'] }}"
      sequence:
        - action: todo.update_item
          data:
            item: "{{ repeat.item.summary }}"
            status: completed
          target:
            entity_id: !input todo_entity
mode: single
